CREATE TABLE USUARIOS(
  USUARIO VARCHAR(25) NOT NULL,
  CONTRASENIA VARCHAR(255) NOT NULL,
  NOMBREAPELLIDOS VARCHAR (100),
  DNI VARCHAR(10),
  TELEFONO INT(9),
  FECHANACIMIENTO DATE,
  EMAIL VARCHAR(100),
  PRIMARY KEY (USUARIO)
);

CREATE TABLE ANIMALES(
  ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(20) NOT NULL,
  ESPECIE VARCHAR(20),
  RAZA VARCHAR(30),
  EDAD VARCHAR(20),
  SEXO CHAR(1) NOT NULL,
  DESCRIPCION LONGTEXT,
  PRIMARY KEY (ID)
);